name       : python-croniter
version    : 1.3.5
release    : 7
source     :
    - https://files.pythonhosted.org/packages/source/c/croniter/croniter-1.3.5.tar.gz : 7592fc0e8a00d82af98dfa2768b75983b6fb4c2adc8f6d0d7c931a715b7cefee
homepage   : https://github.com/kiorky/croniter
license    : MIT
component  : programming.python
summary    : croniter provides iteration for datetime object with cron like format
description: |
    croniter is a python module to provide iteration for datetime object.
builddeps  :
    - python-dateutil
    - python-pytest
    - python-tzlocal
rundeps    :
    - python-dateutil
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3 -v
