name       : python-croniter
version    : 0.3.36
release    : 1
source     :
    - https://files.pythonhosted.org/packages/source/c/croniter/croniter-0.3.36.tar.gz : 9d3098e50f7edc7480470455d42f09c501fa1bb7e2fc113526ec6e90b068f32c
homepage   : https://github.com/taichino/croniter
license    : MIT
component  : programming.python
summary    : croniter provides iteration for datetime object with cron like format
description: |
    croniter is a python module to provide iteration for datetime object.
builddeps  :
    - python-dateutil
    - python-natsort
    - python-pytest
    - python-tzlocal
rundeps    :
    - python-dateutil
    - python-natsort
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3 -v
