name       : python-croniter
version    : 1.4.1
release    : 9
source     :
    - https://files.pythonhosted.org/packages/source/c/croniter/croniter-1.4.1.tar.gz : 1a6df60eacec3b7a0aa52a8f2ef251ae3dd2a7c7c8b9874e73e791636d55a361
homepage   : https://github.com/kiorky/croniter
license    : MIT
component  : programming.python
summary    : croniter provides iteration for datetime object with cron like format
description: |
    croniter is a python module to provide iteration for datetime object.
builddeps  :
    - python-dateutil #
    - python-pytest   #
    - python-pytz     #
rundeps    :
    - python-dateutil
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest -v
