name       : python-croniter
version    : 1.3.4
release    : 6
source     :
    - https://files.pythonhosted.org/packages/source/c/croniter/croniter-1.3.4.tar.gz : 3169365916834be654c2cac57ea14d710e742f8eb8a5fce804f6ce548da80bf2
homepage   : https://github.com/kiorky/croniter
license    : MIT
component  : programming.python
summary    : croniter provides iteration for datetime object with cron like format
description: |
    croniter is a python module to provide iteration for datetime object.
builddeps  :
    - python-dateutil
    - python-pytest
    - python-tzlocal
rundeps    :
    - python-dateutil
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3 -v
